<a href="https://colab.research.google.com/github/sravanilakkoju/Pythonguide/blob/main/chapter_appendix-tools-for-deep-learning/jupyter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Using Jupyter Notebooks
:label:`sec_jupyter`


This section describes how to edit and run the code
in each section of this book
using the Jupyter Notebook. Make sure you have
installed Jupyter and downloaded the
code as described in
:ref:`chap_installation`.
If you want to know more about Jupyter see the excellent tutorial in
their [documentation](https://jupyter.readthedocs.io/en/latest/).


## Editing and Running the Code Locally

Suppose that the local path of the book's code is `xx/yy/d2l-en/`. Use the shell to change the directory to this path (`cd xx/yy/d2l-en`) and run the command `jupyter notebook`. If your browser does not do this automatically, open http://localhost:8888 and you will see the interface of Jupyter and all the folders containing the code of the book, as shown in :numref:`fig_jupyter00`.

![The folders containing the code of this book.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter00.png?raw=1)
:width:`600px`
:label:`fig_jupyter00`


You can access the notebook files by clicking on the folder displayed on the webpage.
They usually have the suffix ".ipynb".
For the sake of brevity, we create a temporary "test.ipynb" file.
The content displayed after you click it is
shown in :numref:`fig_jupyter01`.
This notebook includes a markdown cell and a code cell. The content in the markdown cell includes "This Is a Title" and "This is text.".
The code cell contains two lines of Python code.

![Markdown and code cells in the "text.ipynb" file.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter01.png?raw=1)
:width:`600px`
:label:`fig_jupyter01`


Double click on the markdown cell to enter edit mode.
Add a new text string "Hello world." at the end of the cell, as shown in :numref:`fig_jupyter02`.

![Edit the markdown cell.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter02.png?raw=1)
:width:`600px`
:label:`fig_jupyter02`


As demonstrated in :numref:`fig_jupyter03`,
click "Cell" $\rightarrow$ "Run Cells" in the menu bar to run the edited cell.

![Run the cell.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter03.png?raw=1)
:width:`600px`
:label:`fig_jupyter03`

After running, the markdown cell is shown in :numref:`fig_jupyter04`.

![The markdown cell after running.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter04.png?raw=1)
:width:`600px`
:label:`fig_jupyter04`


Next, click on the code cell. Multiply the elements by 2 after the last line of code, as shown in :numref:`fig_jupyter05`.

![Edit the code cell.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter05.png?raw=1)
:width:`600px`
:label:`fig_jupyter05`


You can also run the cell with a shortcut ("Ctrl + Enter" by default) and obtain the output result from :numref:`fig_jupyter06`.

![Run the code cell to obtain the output.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter06.png?raw=1)
:width:`600px`
:label:`fig_jupyter06`


When a notebook contains more cells, we can click "Kernel" $\rightarrow$ "Restart & Run All" in the menu bar to run all the cells in the entire notebook. By clicking "Help" $\rightarrow$ "Edit Keyboard Shortcuts" in the menu bar, you can edit the shortcuts according to your preferences.

## Advanced Options

Beyond local editing two things are quite important: editing the notebooks in the markdown format and running Jupyter remotely.
The latter matters when we want to run the code on a faster server.
The former matters since Jupyter's native ipynb format stores a lot of auxiliary data that is
irrelevant to the content,
mostly related to how and where the code is run.
This is confusing for Git, making
reviewing contributions very difficult.
Fortunately there is an alternative---native editing in the markdown format.

### Markdown Files in Jupyter

If you wish to contribute to the content of this book, you need to modify the
source file (md file, not ipynb file) on GitHub.
Using the notedown plugin we
can modify notebooks in the md format directly in Jupyter.


First, install the notedown plugin, run the Jupyter Notebook, and load the plugin:

```
pip install d2l-notedown  # You may need to uninstall the original notedown.
jupyter notebook --NotebookApp.contents_manager_class='notedown.NotedownContentsManager'
```

You may also turn on the notedown plugin by default whenever you run the Jupyter Notebook.
First, generate a Jupyter Notebook configuration file (if it has already been generated, you can skip this step).

```
jupyter notebook --generate-config
```

Then, add the following line to the end of the Jupyter Notebook configuration file (for Linux or macOS, usually in the path `~/.jupyter/jupyter_notebook_config.py`):

```
c.NotebookApp.contents_manager_class = 'notedown.NotedownContentsManager'
```

After that, you only need to run the `jupyter notebook` command to turn on the notedown plugin by default.

### Running Jupyter Notebooks on a Remote Server

Sometimes, you may want to run Jupyter notebooks on a remote server and access it through a browser on your local computer. If Linux or macOS is installed on your local machine (Windows can also support this function through third-party software such as PuTTY), you can use port forwarding:

```
ssh myserver -L 8888:localhost:8888
```

The above string `myserver` is the address of the remote server.
Then we can use http://localhost:8888 to access the remote server `myserver` that runs Jupyter notebooks. We will detail on how to run Jupyter notebooks on AWS instances
later in this appendix.

### Timing

We can use the `ExecuteTime` plugin to time the execution of each code cell in Jupyter notebooks.
Use the following commands to install the plugin:

```
pip install jupyter_contrib_nbextensions
jupyter contrib nbextension install --user
jupyter nbextension enable execute_time/ExecuteTime
```

## Summary

* Using the Jupyter Notebook tool, we can edit, run, and contribute to each section of the book.
* We can run Jupyter notebooks on remote servers using port forwarding.


## Exercises

1. Edit and run the code in this book with the Jupyter Notebook on your local machine.
1. Edit and run the code in this book with the Jupyter Notebook *remotely* via port forwarding.
1. Compare the running time of the operations $\mathbf{A}^\top \mathbf{B}$ and $\mathbf{A} \mathbf{B}$ for two square matrices in $\mathbb{R}^{1024 \times 1024}$. Which one is faster?


[Discussions](https://discuss.d2l.ai/t/421)


In [4]:
import numpy as np

a = np.array([1,2,3],dtype='int16') #e can also specify the data type we need
a


array([1, 2, 3], dtype=int16)

In [5]:
b = np.array([[1,2,3,4,5],[1.2,2.5,5.3,6.9,1.2]])
b

array([[1. , 2. , 3. , 4. , 5. ],
       [1.2, 2.5, 5.3, 6.9, 1.2]])

In [6]:
b.ndim #get the dimention of the array

2

In [7]:
#get shape
b.shape

(2, 5)

In [8]:
#get the type
print(b.dtype)
a.dtype

float64


dtype('int16')

In [9]:
# get size
print(a.itemsize)
print(b.itemsize)

2
8


In [10]:
#get the total size
print(a.size)
print(b.size)


3
10


**Accessing or changing the specific elements using numpy.**

In [11]:
a = np.array([[1,2,3,4,5,6,7,8],[4,5,16,7,6,5,9,8]])
print(a.ndim)

2


In [12]:
print(a)

[[ 1  2  3  4  5  6  7  8]
 [ 4  5 16  7  6  5  9  8]]


In [13]:
#get a specific element[r,c]
print(a[1,4])
#negitive indexing
print(a[-1,-3])

6
5


In [14]:
#get a specific row
print(a[0])
print(a[0,:])

[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]


In [15]:
#get a specific column
a[:,1] #doesnot gives the specified output
#[startindex:endindex:stepindex]
print(a[0,1:6:2])
print(a[0,1:-1:2])

[2 4 6]
[2 4 6]


In [16]:
print(a[1,5])

5


In [17]:
a[1,5] = 20
print(a)

a[:,2] = 5
print(a)

a[:,2] = [1,9]
print(a)


[[ 1  2  3  4  5  6  7  8]
 [ 4  5 16  7  6 20  9  8]]
[[ 1  2  5  4  5  6  7  8]
 [ 4  5  5  7  6 20  9  8]]
[[ 1  2  1  4  5  6  7  8]
 [ 4  5  9  7  6 20  9  8]]


**3-d example**

In [18]:
b = np.array([[[1, 28, 3], [41, 51, 6]], [[11, 21, 13], [5, 5, 9]]])

print(b)

[[[ 1 28  3]
  [41 51  6]]

 [[11 21 13]
  [ 5  5  9]]]


In [19]:
#get specific elements(ork outside in)
print(b[0,1,2])
print(b[:,1,:])
print(b[:,0,:])

6
[[41 51  6]
 [ 5  5  9]]
[[ 1 28  3]
 [11 21 13]]


In [20]:
b[:,1,:] = [[9,9,9],[8,8,8]]
print(b)

[[[ 1 28  3]
  [ 9  9  9]]

 [[11 21 13]
  [ 8  8  8]]]


**Initializing different types of arrays**

In [21]:
# all zeros matrix
print(np.zeros(5))
print(np.zeros((2,6)))

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [22]:
#all one's matrix
print(np.ones(4))
print(np.ones((3,3), dtype= 'int16'))
#print(itemsize(np.ones((3,3), dtype= 'int16'))) - wrong
print((np.ones((3,3), dtype= 'int16')).itemsize)
print(np.ones((2,3,5),dtype = 'float32'))
print((np.ones((2,3,5),dtype = 'float32')).itemsize)

[1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
2
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
4


In [23]:
#any other number
print(np.full((3,2),99,dtype = 'float32'))
# Set print options to display float numbers with two decimal places
np.set_printoptions(formatter={'float_kind': '{:.2f}'.format})
print(np.full((3,2),99,dtype = 'float32'))

[[99. 99.]
 [99. 99.]
 [99. 99.]]
[[99.00 99.00]
 [99.00 99.00]
 [99.00 99.00]]


In [24]:
#any other number(full_like)
print(np.full_like(a,4))

[[4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4]]


In [25]:
print(np.full(a.shape,5))

[[5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]]


#Random decimal numbers


In [26]:
#rand() method returns a random float between 0 and 1
print(np.random.rand(4,2))
print(np.random.rand(4,2,3))

[[0.30 0.85]
 [0.67 0.10]
 [0.65 1.00]
 [0.76 0.75]]
[[[0.04 0.23 0.14]
  [0.09 0.89 0.22]]

 [[0.54 0.54 0.82]
  [0.82 0.86 0.45]]

 [[0.49 1.00 0.95]
  [0.19 0.44 0.19]]

 [[0.05 0.64 0.93]
  [0.62 0.48 0.63]]]


In [27]:
from numpy import random
x = random.rand(4,2)
print(x)
x1=np.random.randint(100, size=(5))
print(x1)

[[0.98 0.70]
 [0.36 0.03]
 [0.34 0.13]
 [0.63 0.46]]
[22  7  3 26 24]


In [28]:
print(np.random.random_sample(a.shape)) #another method

[[0.32 0.30 0.09 0.39 0.90 0.57 0.38 0.55]
 [0.57 0.77 0.47 0.26 0.83 0.50 0.35 0.81]]


In [29]:
#random intreger values
print(random.randint(20,size=(2,2)))

random.randint(-2,7,size=(3,3)) #(startvalue,endvalue,matrixsize)

[[18  7]
 [ 6  0]]


array([[1, 2, 1],
       [6, 3, 3],
       [3, 0, 6]])

In [30]:
#identity matrix
print(np.identity(3))
print(np.identity((4),dtype='int16'))

[[1.00 0.00 0.00]
 [0.00 1.00 0.00]
 [0.00 0.00 1.00]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [31]:
#repeat an array...
arr = np.array([1,2,3])
r1 = np.repeat(arr,3,axis = 0)
print(r1)

arr1 = np.array([[4,5,6]])
r2 = np.repeat(arr1,3,axis = 0)
print(r2)

arr2 = np.array([[4,5,6]])
r3 = np.repeat(arr2,5,axis = 1)
print(r3)

[1 1 1 2 2 2 3 3 3]
[[4 5 6]
 [4 5 6]
 [4 5 6]]
[[4 4 4 4 4 5 5 5 5 5 6 6 6 6 6]]


In [32]:
'''
1 1 1 1 1
1 0 0 0 1
1 0 9 0 1
1 0 0 0 1
1 1 1 1 1
'''
output = np.ones((5,5),dtype='int32')
print(output)

z = np.zeros((3,3),dtype='int32')
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [33]:
'''
1 1 1 1 1
1 0 0 0 1
1 0 9 0 1
1 0 0 0 1
1 1 1 1 1
'''
output = np.ones((5,5),dtype='int32')
print(output)

z = np.zeros((3,3),dtype='int32')
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


be careful when copying arrays

In [34]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [38]:
#make the direct copy of the array a
b = a
print(b)
b[0] = 1000
print(b)
print(a)# here a is also changing because e directly assigned the value and changes are
#done also for the contents of a...


[1000    2    3]
[1000    2    3]
[1000    2    3]


In [40]:
# cop function to mae a copy of an array
b = a.copy()
print(b)
b[0] = 10 # tghis doent change the contents of a
print(b)
print(a)

[1000    2    3]
[10  2  3]
[1000    2    3]


**Mathematical Operations**

In [44]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [46]:
print(a + 2) # this adds the no.  to all elements of the array

[3 4 5]


In [47]:
print(a-1)

[0 1 2]


In [48]:
print(a*2)

[2 4 6]


In [49]:
print(a/2)

[0.50 1.00 1.50]


In [51]:
b = np.array([1,3,6])
print(a+b)

[2 5 9]


In [52]:
print(b**2)

[ 1  9 36]


In [53]:
#take the sin
np.sin(a)

array([0.84, 0.91, 0.14])

In [54]:
np.cos(b)

array([0.54, -0.99, 0.96])

# Linear Algebra

In [60]:
a = np.ones((2,3),dtype='int16')
print(a)

b = np.full((3,2),2)
print(b)

print(a*b) # this doesnot multiply the matrix insted throws an error

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [64]:
d = np.matmul(a,b)
print(d) # matrixmul method to multiply two matrix

[[6 6]
 [6 6]]


In [62]:
#determinent of the identity matrix
c = np.identity(3)
print(np.linalg.det(c))

1.0


In [66]:
print(np.linalg.det(d))

0.0


https://numpy.org/doc/stable/reference/routines.linalg.html

referance material

**statistics**

In [70]:
stats = np.array([[11,2,3],[4,5,61]])
print(stats)

[[11  2  3]
 [ 4  5 61]]


In [71]:
print(np.min(stats))


2


In [72]:
print(np.max(stats))

61


In [74]:
print(np.min(stats,axis = 0)) #axis = 0 - Computes the minimum/maximum for each column

[4 2 3]


In [77]:
print(np.max(stats,axis = 1)) #axis = 1 - Computes the minimum/maximum for each row

[11 61]


In [82]:
# Initialize p with the correct shape (3,) and a suitable data type (e.g., the same as stats)
p = np.empty(stats.shape[1], dtype=stats.dtype)
np.min(stats, axis=0, out=p) #axis = 0 - Computes the minimum/maximum for each column
print(p)

[4 2 3]


In [83]:
print(np.sum(stats))

86


In [85]:
print(np.sum(stats,axis = 1))# finds the sum fro each row

[16 70]


In [88]:
before = np.array([[1,2,3,9],[4,5,6,7]])
print(before)
print(before.shape)

[[1 2 3 9]
 [4 5 6 7]]
(2, 4)


In [94]:
# reshaping the matrix by specifing the shape
# if the given size is not compatable it throws a valueError
after = before.reshape((8,1))
print(after)
after = before.reshape((2,2,2))
print(after)
after = before.reshape((4,2))
print(after)

[[1]
 [2]
 [3]
 [9]
 [4]
 [5]
 [6]
 [7]]
[[[1 2]
  [3 9]]

 [[4 5]
  [6 7]]]
[[1 2]
 [3 9]
 [4 5]
 [6 7]]


In [98]:
# vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(np.vstack([v1,v2,v2,v1]))

[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [1 2 3 4]]


In [102]:
# horizontal stacking
print(np.hstack((v1,v2,v1)))

[1 2 3 4 5 6 7 8 1 2 3 4]


In [104]:
#horizontal stack
h1 = np.ones((2,4),dtype='int32')
h2 = np.zeros((2,2),dtype='int32')
print(h1)
print(h2)
print(np.hstack((h1,h2)))

[[1 1 1 1]
 [1 1 1 1]]
[[0 0]
 [0 0]]
[[1 1 1 1 0 0]
 [1 1 1 1 0 0]]


**Miscellaneous**

**Load data from the file**